# Generated by Django 4.2.10 on 2024-12-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_text_paragraph_alter_text_subtext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='pic.jpg', upload_to=''),
        ),
    ]
