# Generated by Django 4.2.10 on 2024-12-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='Github',
            new_name='links',
        ),
        migrations.RemoveField(
            model_name='link',
            name='Gmail',
        ),
        migrations.RemoveField(
            model_name='link',
            name='LinkedIn',
        ),
        migrations.RemoveField(
            model_name='link',
            name='facebook_link',
        ),
    ]
